#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Incorrect number of arguments passed."
    exit 1
fi

if [ ! -d $1 ]; then
    echo "'$1' is not a valid directory."
    exit 1
fi

pyboardPath="$1/pyboard"
if [ ! -d $pyboardPath ]; then
    echo "'$pyboardPath' is not a valid directory."
    exit 1
fi

prescript="$1/pre-script.py"
if [ -f $prescript ]; then
    echo "Running pre script."
    python $prescript
    echo "Finished running pre script."
else
    echo "No pre script found."
fi

# File to store the timestamp of the last upload
timestampFile=".last_upload_timestamp"
currentTimestamp=$(date +%s)

if [ -f $timestampFile ]; then
    lastUploadTimestamp=$(cat $timestampFile)
else
    # If the file does not exist, assume the last upload was a long time ago.
    lastUploadTimestamp=0
fi

# Find changed files since the last upload and copy them to the pyboard
find $pyboardPath -type f -newermt "@$lastUploadTimestamp" | while IFS= read -r file; do
    destination="/pyboard/${file#$pyboardPath/}"
    echo "Copying changed file: $file -> $destination"
    rshell cp "$file" "$destination"
done

# Update the timestamp of the last upload
echo $currentTimestamp > $timestampFile

rshell repl \~ "exec(open('/main.py').read())"
